// examples/vue/src/App.vue
<script setup lang="ts">
import { ref } from "vue";
import { ErrorCorrectionLevel, ErrorCorrectionLevelType } from "@qrgrid/core";

import Canvas from "./canvas/Index.vue";
import Svg from "./svg/Index.vue";

const input = ref("");
const errorCorrection = ref<ErrorCorrectionLevelType>("M");

const FINDER_COLOR = "#ff3131";
</script>

<template>
  <div className="inputContainer">
    <textarea
      placeholder="Text To Encode"
      v-model="input"
      :rows="4"
      :cols="50"
    />
    <select
      name="errorCorrection"
      id="errorCorrection"
      :defaultValue="ErrorCorrectionLevel.M"
      v-model="errorCorrection"
    >
      <option disabled>Choose a ErrorCorrectionLevel</option>
      <option
        v-for="ec in Object.keys(ErrorCorrectionLevel)"
        :key="ec"
        :value="ec"
      >
        {{ ec }}
      </option>
    </select>
  </div>
  <h2 :style="{ margin: '2rem', borderBottom: '1px solid' }">Using Canvas</h2>
  <Canvas
    :input="input"
    :qrOptions="{ errorCorrection }"
    :finderColor="FINDER_COLOR"
  />
  <h2 :style="{ margin: '2rem', borderBottom: '1px solid' }">Using Svg</h2>
  <Svg
    :input="input"
    :qrOptions="{ errorCorrection }"
    :finderColor="FINDER_COLOR"
  />
</template>

// examples/angular/src/app/app.component.ts
import { Component } from '@angular/core';
import { RouterOutlet } from '@angular/router';
import { FormControl, ReactiveFormsModule } from '@angular/forms';
import { CanvasComponent } from './canvas/canvas.component';
import { SvgComponent } from './svg/svg.component';
import { ErrorCorrectionLevelType } from '@qrgrid/core';

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [ReactiveFormsModule, RouterOutlet, CanvasComponent, SvgComponent],
  templateUrl: './app.component.html',
  styleUrl: './app.component.css',
})
export class AppComponent {
  inputText = new FormControl('');
  errorCorrection = new FormControl<ErrorCorrectionLevelType>('M', {
    nonNullable: true,
  });

  FINDER_COLOR = '#ff3131';
}

<div class="inputContainer">
  <textarea id="inputText" [formControl]="inputText" placeholder="Text To Encode" rows=4 cols=50> </textarea>
  <select name="errorCorrection" id="errorCorrectionSelect" [formControl]="errorCorrection">
    <option disabled>Choose a ErrorCorrectionLevel</option>
    <option value="L">L</option>
    <option value="M" selected>M</option>
    <option value="Q">Q</option>
    <option value="H">H</option>
  </select>

  <h2 style="margin: 2rem;border-bottom:1px solid;">
    Using Canvas
  </h2>
  <app-canvas [input]="inputText.value || ''" [errorCorrection]="errorCorrection.value" [finderColor]="FINDER_COLOR" />

  <h2 style="margin: 2rem;border-bottom:1px solid;">
    Using Svg
  </h2>
  <app-svg [input]="inputText.value || ''" [errorCorrection]="errorCorrection.value" [finderColor]="FINDER_COLOR" />
</div>

<router-outlet />
